name: Hello World workflow
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Hello world action step
          run: echo "Hello world!"
          shell: bash

    goodBye:
        runs-on: ubuntu-latest
        steps:
        - name: Goodbye world action step
          run: echo "Goodbye world!"
          shell: bash


